// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendFolder(arg1:string):Promise<Array<main.TrackInfo>>;

export function GetCover(arg1:number):Promise<string>;

export function GetCurrentTrack():Promise<main.TrackInfo>;

export function GetLoopMode():Promise<number>;

export function GetQueue():Promise<Array<main.TrackInfo>>;

export function GetRPCEnabled():Promise<boolean>;

export function GetShuffle():Promise<boolean>;

export function GetVolume():Promise<number>;

export function LoadFolder(arg1:string):Promise<Array<main.TrackInfo>>;

export function Next():Promise<void>;

export function Pause():Promise<void>;

export function PickFolder():Promise<Array<main.TrackInfo>>;

export function PickFolderAppend():Promise<Array<main.TrackInfo>>;

export function PlayFile(arg1:string):Promise<void>;

export function PlayTrack(arg1:number):Promise<void>;

export function Prev():Promise<void>;

export function Resume():Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetLoopMode(arg1:number):Promise<void>;

export function SetRPCEnabled(arg1:boolean):Promise<void>;

export function SetShuffle(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;
