// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ytm} from '../models';

export function AppendFolder(arg1:string):Promise<Array<main.TrackInfo>>;

export function CancelAllDownloads():Promise<void>;

export function ClearQueue():Promise<Array<main.TrackInfo>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetCover(arg1:number):Promise<string>;

export function GetCurrentTrack():Promise<main.TrackInfo>;

export function GetLoopMode():Promise<number>;

export function GetQueue():Promise<Array<main.TrackInfo>>;

export function GetRPCEnabled():Promise<boolean>;

export function GetShuffle():Promise<boolean>;

export function GetVolume():Promise<number>;

export function GetYTMArtist(arg1:string):Promise<ytm.Artist>;

export function GetYTMPlaylist(arg1:string):Promise<ytm.Playlist>;

export function GetYTMRadio(arg1:string):Promise<Array<main.TrackInfo>>;

export function GetYTMSongLyrics(arg1:string):Promise<string>;

export function GetYTMSuggestions(arg1:string):Promise<Array<string>>;

export function InsertYTMSongAt(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<Array<main.TrackInfo>>;

export function LoadFolder(arg1:string):Promise<Array<main.TrackInfo>>;

export function Next():Promise<void>;

export function Pause():Promise<void>;

export function PickFolder():Promise<Array<main.TrackInfo>>;

export function PickFolderAppend():Promise<Array<main.TrackInfo>>;

export function PlayFile(arg1:string):Promise<void>;

export function PlayTrack(arg1:number):Promise<void>;

export function PlayYTMSong(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function Prev():Promise<void>;

export function RemoveFromQueue(arg1:number):Promise<Array<main.TrackInfo>>;

export function ReorderQueue(arg1:number,arg2:number):Promise<Array<main.TrackInfo>>;

export function Resume():Promise<void>;

export function SearchYTM(arg1:string,arg2:string):Promise<ytm.SearchResults>;

export function SearchYTMMore(arg1:string):Promise<main.SearchContinuationResult>;

export function SearchYTMViewMore(arg1:string):Promise<Array<ytm.MediaItem>>;

export function Seek(arg1:number):Promise<void>;

export function SetLoopMode(arg1:number):Promise<void>;

export function SetRPCEnabled(arg1:boolean):Promise<void>;

export function SetShuffle(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function UpdateConfig(arg1:main.AppConfig):Promise<void>;
