// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendFolder(arg1) {
  return window['go']['main']['App']['AppendFolder'](arg1);
}

export function CancelAllDownloads() {
  return window['go']['main']['App']['CancelAllDownloads']();
}

export function ClearQueue() {
  return window['go']['main']['App']['ClearQueue']();
}

export function GetCover(arg1) {
  return window['go']['main']['App']['GetCover'](arg1);
}

export function GetCurrentTrack() {
  return window['go']['main']['App']['GetCurrentTrack']();
}

export function GetLoopMode() {
  return window['go']['main']['App']['GetLoopMode']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetRPCEnabled() {
  return window['go']['main']['App']['GetRPCEnabled']();
}

export function GetShuffle() {
  return window['go']['main']['App']['GetShuffle']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function GetYTMArtist(arg1) {
  return window['go']['main']['App']['GetYTMArtist'](arg1);
}

export function GetYTMPlaylist(arg1) {
  return window['go']['main']['App']['GetYTMPlaylist'](arg1);
}

export function GetYTMRadio(arg1) {
  return window['go']['main']['App']['GetYTMRadio'](arg1);
}

export function GetYTMSongLyrics(arg1) {
  return window['go']['main']['App']['GetYTMSongLyrics'](arg1);
}

export function GetYTMSuggestions(arg1) {
  return window['go']['main']['App']['GetYTMSuggestions'](arg1);
}

export function InsertYTMSongAt(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['InsertYTMSongAt'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LoadFolder(arg1) {
  return window['go']['main']['App']['LoadFolder'](arg1);
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickFolderAppend() {
  return window['go']['main']['App']['PickFolderAppend']();
}

export function PlayFile(arg1) {
  return window['go']['main']['App']['PlayFile'](arg1);
}

export function PlayTrack(arg1) {
  return window['go']['main']['App']['PlayTrack'](arg1);
}

export function PlayYTMSong(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PlayYTMSong'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Prev() {
  return window['go']['main']['App']['Prev']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function ReorderQueue(arg1, arg2) {
  return window['go']['main']['App']['ReorderQueue'](arg1, arg2);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SearchYTM(arg1, arg2) {
  return window['go']['main']['App']['SearchYTM'](arg1, arg2);
}

export function SearchYTMMore(arg1) {
  return window['go']['main']['App']['SearchYTMMore'](arg1);
}

export function SearchYTMViewMore(arg1) {
  return window['go']['main']['App']['SearchYTMViewMore'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetLoopMode(arg1) {
  return window['go']['main']['App']['SetLoopMode'](arg1);
}

export function SetRPCEnabled(arg1) {
  return window['go']['main']['App']['SetRPCEnabled'](arg1);
}

export function SetShuffle(arg1) {
  return window['go']['main']['App']['SetShuffle'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}
