// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentTrack():Promise<main.TrackInfo>;

export function GetQueue():Promise<Array<main.TrackInfo>>;

export function GetVolume():Promise<number>;

export function LoadFolder(arg1:string):Promise<Array<main.TrackInfo>>;

export function Next():Promise<void>;

export function Pause():Promise<void>;

export function PickFolder():Promise<Array<main.TrackInfo>>;

export function PlayFile(arg1:string):Promise<void>;

export function PlayTrack(arg1:number):Promise<void>;

export function Prev():Promise<void>;

export function Resume():Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;
