// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentTrack() {
  return window['go']['main']['App']['GetCurrentTrack']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function LoadFolder(arg1) {
  return window['go']['main']['App']['LoadFolder'](arg1);
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PlayFile(arg1) {
  return window['go']['main']['App']['PlayFile'](arg1);
}

export function PlayTrack(arg1) {
  return window['go']['main']['App']['PlayTrack'](arg1);
}

export function Prev() {
  return window['go']['main']['App']['Prev']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}
