name: Build Binaries

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows GUI"
            os: windows
            arch: amd64
            tags: ""
            path: "./cmd/gui"
            output: "OngoPlayer-gui-windows.exe"
            install_deps: true


          - name: "Linux X11 OpenGL GUI"
            os: linux
            arch: amd64
            tags: "-tags nowayland"
            path: "./cmd/gui"
            output: "OngoPlayer-gui-linux-x11gl"
            install_deps: true

          - name: "Linux Wayland OpenGL GUI"
            os: linux
            arch: amd64
            tags: "-tags nox11"
            path: "./cmd/gui"
            output: "OngoPlayer-gui-linux-wayopengl"
            install_deps: true

          - name: "Linux Wayland Vulkan GUI"
            os: linux
            arch: amd64
            tags: "-tags nox11,noopengl"
            path: "./cmd/gui"
            output: "OngoPlayer-gui-linux-wayvulkan"
            install_deps: true


    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"

      - name: Install Dependencies
        if: matrix.install_deps == true
        run: |
          sudo apt-get update
          if [ "${{ matrix.os }}" = "linux" ]; then
            sudo apt-get install -y gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev libasound2-dev
          elif [ "${{ matrix.os }}" = "windows" ]; then
            sudo apt-get install -y nsis zstd
          fi

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.name }}" = "Windows GUI" ]; then
            go run gioui.org/cmd/gogio@latest -target windows -icon ./cmd/gui/assets/appicon.png -o build/${{ matrix.output }} ${{ matrix.path }}
          else
            go build ${{ matrix.tags }} -o build/${{ matrix.output }} ${{ matrix.path }}
          fi

      - name: Build Windows Installer
        if: matrix.name == 'Windows GUI'
        run: |
          mkdir -p build/win
          cp build/${{ matrix.output }} build/win/OngoPlayer.exe
          go run tools/download_win_deps.go
          makensis tools/installer.nsi

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.output }}
          path: build/${{ matrix.output }}

      - name: Upload Windows Installer
        if: matrix.name == 'Windows GUI'
        uses: actions/upload-artifact@v7
        with:
          name: OngoPlayer_Installer
          path: build/OngoPlayer_Installer.exe
